---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kube-app-test
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/sreenubk/kube-app-test
