---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-app-test
  namespace: flux-system
spec:
  interval: 3m20s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-app-test
  targetNamespace: default
